### ISSUE TITLE
How to use the API?

### ISSUE THREAD

**Issue by KaitoZerjoYT** [NoteLand/WDForms#1]
Hey,

I was wondering how to use the API, like how to create all those forms and query the buttons, input fields, etc. It would be nice if you could explain it to me

**Comment by Crasher508** [comment]
Very simple: Example for SimpleForm, implementations for ModalForm and CustomForm are similar

```java
SimpleForm form = new SimpleForm(((proxiedPlayer, response) -> {
            proxiedPlayer.sendMessage(response + " this is an int");
}));
form.setTitle("Title");
form.setContent("Content");
form.addButton("Button");
Forms.getInstance().sendForm(player, form);
```

Please do not abuse issue section for questions. Have a nice evening :)
